### ISSUE TITLE
dovetail-cli install script fails to generate $GOPATH/bin

### ISSUE THREAD

**Issue by fzuchows** [TIBCOSoftware/dovetail-cli#40]
drwxr-xr-x 11 tibco tibco 4096 Mar 22 17:52 ../
tibco@ub1664blckchn:~/dovetail-cli$ curl -sSL https://github.com/TIBCOSoftware/dovetail-cli/releases/download/v0.1.2/dovetail-cli-install.sh > install.sh && source install.sh

===> Creating dovetail-cli directory
===> Setting GOPATH to /home/tibco/dovetail-cli/dovetail-cli
===> Getting github.com/TIBCOSoftware/dovetail-cli repository this might take a few minutes
# github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/core/operations
src/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/core/operations/system.go:227:23: not enough arguments in call to s.statsd.SendLoop
        have (<-chan time.Time, string, string)
        want (context.Context, <-chan time.Time, string, string)
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$ echo $GOPATH
/home/tibco/dovetail-cli/dovetail-cli
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$ go version
go version go1.11.6 linux/amd64
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$

**Comment by fzuchows** [comment]
Result
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$ ll
total 16
drwxrwxr-x 4 tibco tibco 4096 Mar 22 17:57 ./
drwxrwxr-x 3 tibco tibco 4096 Mar 22 17:52 ../
-rw-rw-r-- 1 tibco tibco    0 Mar 22 17:57 Creating
-rw-rw-r-- 1 tibco tibco    0 Mar 22 17:57 Getting
-rw-rw-r-- 1 tibco tibco    0 Mar 22 17:57 install.sh
drwxrwxr-x 3 tibco tibco 4096 Mar 22 17:54 pkg/
-rw-rw-r-- 1 tibco tibco    0 Mar 22 17:57 Setting
drwxrwxr-x 7 tibco tibco 4096 Mar 22 17:54 src/
tibco@ub1664blckchn:~/dovetail-cli/dovetail-cli$

**Comment by yxuco** [comment]
Did you try the Makefile as described in https://github.com/TIBCOSoftware/dovetail-cli/blob/master/README.md

**Comment by yxuco** [comment]
If you are on ubuntu, the READM also describes a solution for this error in the troubleshooting section.

**Comment by fzuchows** [comment]
Thank you very much for the prompt response. 
Y, using Ubuntu 16.04.

The page you refer to says "build failing"...
So any impact related to the "build failed" statement to the workaround described in the README ?

Also I use Go11.6. based on https://tibcosoftware.github.io/dovetail/getting-started/getting-started-cli/ which says Go 1.11.x but the README says "...current version of Fabric SDK supports Go 1.11.0-1.11.4...."
Could you please let me know if I have to downgrade ? 

Thank you very much in advance.

**Comment by fzuchows** [comment]
Sorry, typo I use Go 1.11.6

**Comment by yxuco** [comment]
yes, the easiest way to get fabric-sdk-go to compile is to point GOROOT to a Go 1.11.4, unless you edit the makefile of fabric-sdk-go, which I did not try.

**Comment by yxuco** [comment]
You may also try to edit the file fabric-sdk-go/ci.properties to make GO_MAX_VER=1.11.6, and see if you can build and test the fabric-sdk-go as described in the README. Let me know if it works.

**Comment by yxuco** [comment]
I just tested that it works with Go1.11.6. (1) edit fabric-sdk-go/ci.properties to make GO_MAX_VER=1.11.6, (2) in fabric-sdk-go, run "make depend" and "make unit-test", (3) in dovetail-cli, run "make"

**Comment by fzuchows** [comment]
Downgraded to Go 1.11.4 still the same issue.

1.) Removed folder dovetail-cli, downgraded to Golang 1.11.4 and re-run the script under https://tibcosoftware.github.io/dovetail/getting-started/getting-started-cli/
2.) Run again: $> curl -sSL https://github.com/TIBCOSoftware/dovetail-cli/releases/download/v0.1.2/dovetail-cli-install.sh > install.sh && source install.sh

Same results:
++++++++++++++++++++++++++++++++++
tibco@ub1664blckchn:~$ curl -sSL https://github.com/TIBCOSoftware/dovetail-cli/releases/download/v0.1.2/dovetail-cli-install.sh > install.sh && source install.sh
===> Creating dovetail-cli directory
===> Setting GOPATH to /home/tibco/dovetail-cli
===> Getting github.com/TIBCOSoftware/dovetail-cli repository this might take a few minutes
# github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/core/operations
src/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/core/operations/system.go:227:23: not enough arguments in call to s.statsd.SendLoop
        have (<-chan time.Time, string, string)
        want (context.Context, <-chan time.Time, string, string)
tibco@ub1664blckchn:~/dovetail-cli$
....
tibco@ub1664blckchn:~/dovetail-cli$ go version
go version go1.11.4 linux/amd64
tibco@ub1664blckchn:~/dovetail-cli$
++++++++++++++++++++++++++++++++++  

Please note the "have" and "want" in the result...

**Comment by yxuco** [comment]
Frank, please see the previous message for the 3-step "make" process to build/install the dovetail-cli. I tested it yesterday with both Go1.11.4 and Go1.11.6 on ubuntu. 

If you have already run the failed install.sh, you should have downloaded the dovetail-cli source code under $PWD/src/github.com/TIBCOSoftware/dovetail-cli.  Make sure that the env $GOPATH is set to $PWD, and then go to the dovetail-cli source directory to run "make", which should download all dovetail dependencies.  You can then find the fabric-sdk-go source folder under $GOPATH/src/github.com/hyperledger/fabric-sdk-go, and use the Makefile there to download dependencies of the fabric-sdk-go (as described in the previous message.
